// <auto-generated />
namespace MedicalMgmt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class a3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a3));
        
        string IMigrationMetadata.Id
        {
            get { return "201803301651176_a3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
